-- Taiyou Crash File--
This log file has been written on:
2020-08-18 13:23:19.897628

Traceback:
Traceback (most recent call last):
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/main.py", line 26, in <module>
    Taiyou.Run()
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/ENGINE/MAIN/__init__.py", line 214, in Run
    GameObject.Update()
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/Fogoso/MAIN/__init__.py", line 184, in Update
    CurrentUpdate.Update()
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/Fogoso/MAIN/Screens/Game/__init__.py", line 266, in Update
    IncomingLog.Update()
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/Fogoso/MAIN/Screens/Game/IncomingLog/__init__.py", line 104, in Update
    AddMoney(TextGrind_Value[x])
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/Fogoso/MAIN/Screens/Game/IncomingLog/__init__.py", line 134, in AddMoney
    gameMain.DefaultCnt.PlaySound("/hit_1.wav", 0.35)
  File "/home/abacate/Projetos/Python/Taiyou Game Engine/ENGINE/CONTENT_MANAGER/__init__.py", line 696, in PlaySound
    sound = self.AllLoadedSounds[self.AllLoadedSounds.index(SourceName)]
ValueError: '/hit_1.wav' is not in list


Modules Version:
Runtime: 2.9

AppData: 1.0

ContentManager: 2.0

Fx: 1.0

Main: 3.3

Shape: 2.0

Utils: 1.8